name: Publishing my-pkg

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: yarns build

      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
          scope: "@obolnetwork"

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: 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